/**
 * Created by Juan on 23/05/2016.
 *
 */

class CodeBlockCheck {
    private String selectedText;

    CodeBlockCheck(String selectedText) {
        this.selectedText = selectedText;
    }

    /**
     * I'm not entirely sure why I am using "invoke", it was auto-generated by intelliJ when I extracted the method
     * @return isCodeBlock? it checks if the selected code is balanced (amount of "{" and "}") and other minor checks.
     */
    boolean invoke() {
        int leftBalance = 1;
        boolean stopCount = false;
        boolean singleStop = false;
        boolean multiLineStop = false;
        boolean doubleStop = false;


        char[] chars = selectedText.toCharArray();
        int i;

        /**
         * IMPORTANT! I don't care about <!-- or --> comments on js (yes, they exist).
         * If you happen to use that kind of comment, you deserve no respect nor compatible plugins
         * ...
         * you monster.
         */

        for (i = selectedText.indexOf('{') + 1; i < chars.length && leftBalance > 0; i++) {
            switch (chars[i]) {
                // Stop counting when a string opens
                case '"':
                    if (i > 0 && chars[i - 1] != '\\') {
                        if (!singleStop) {
                            stopCount = !stopCount;
                            doubleStop = !doubleStop;
                        }
                    }
                    break;
                // Stop counting when a string opens
                case '\'':
                    if (i > 0 && chars[i - 1] != '\\') {
                        if (!doubleStop) {
                            stopCount = !stopCount;
                            singleStop = !singleStop;
                        }
                    }
                    break;
                // Stop counting when a comment opens
                case '/':
                    if (i + 1 < chars.length)
                        if (chars[i + 1] == '/') {
                            stopCount = true;
                        } else if (chars[i + 1] == '*') {
                            stopCount = true;
                            multiLineStop = true;
                        } else if (multiLineStop && chars[i - 1] == '*') {
                            multiLineStop = false;
                            stopCount = false;
                        }
                    break;
                // Continue counting when a line breaks outside a string or comment
                case '\n':
                    if (i > 0)
                        if ((!(singleStop || doubleStop) || (chars[i - 1] != '\\')) && !multiLineStop) {
                            stopCount = false;
                        }
                    break;
                // Check balance
                case '{':
                    if (!stopCount) {
                        ++leftBalance;
                    }
                    break;
                // Check balance
                case '}':
                    if (!stopCount) {
                        --leftBalance;
                    }
                    break;
            }
        }
        return leftBalance == 0 && selectedText.substring(i).matches("(\\s|;)*");
    }
}
